### 注册用户
POST http://0.0.0.0:18080/api/v1/auth/register
Content-Type: application/json

{
  "username": "bagaking",
  "email": "bagaking@example.com",
  "password": "strongpassword123",
  "confirmPassword": "strongpassword123"
}

### 用户登录
POST http://0.0.0.0:18080/api/v1/auth/login
Content-Type: application/json

{
  "username": "bagaking",
  "password": "strongpassword123"
}

### 刷新Token
POST http://0.0.0.0:18080/api/v1/auth/refresh
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{}

### 获取用户信息（需要认证）
GET http://0.0.0.0:18080/api/v1/session/validate
Authorization: Bearer {{ACCESS_TOKEN}}