// Package repository provides ORM-related operations, adapting SQL type databases.
//
// This file was generated by setup_project.sh script.
package repository

// TODO: Implement ORM-related operations, adapting SQL type databases.
