version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
    environment:
      - RANGER_ENV=dev
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - ranger_iam-net
    entrypoint: [ "/bin/sh", "-c" ] # 覆盖 Dockerfile 的 ENTRYPOINT/CMD
    command: [ "echo 'The app service is started but actual command will be executed manually.' && tail -f /dev/null" ] # 保持容器运行，但不执行应用

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: ranger_iam
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ../deployment/migration:/migration
      - ../deployment/migration/migrate.sh:/migrate.sh
    networks:
      - ranger_iam-net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ranger_iam-net

networks:
  ranger_iam-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local